version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  
    commands:
      - echo "Listing all files and directories:"
      - ls -al
      - cd backend
      - echo "Installing dependencies..."
      - npm install
  
artifacts:
  files:
    - '**/*'
